### ISSUE TITLE
Open TODOs in mostly Ruby related docs

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#25]
## Files marked with TODOs

- `wiki/autotest`  ▶︎ TODO: Keep it or delete it? Note: No active pages link here
- `cucumber/environment variables` ▶︎ TODO: Make more general (seems to be a mix of Ruby and JVM?) Note: the following pages link here: `cucumber.yml` (but is not currently active)
`implementations/ruby/debugging` ▶︎ TODO: Review for length Note: `environment-variables` links here (but is not currently active)
- `/wiki/cucumber-backgrounder/` ▶︎ TODO: Blog post intro or some such (FYI: I did some editing in this already, on branch `backgrounder`) Note: No active pages link here
- `cucumber/step-arguments-transforms` ▶︎ TODO: Ruby specific feature. generalize. Note: No active pages link here
- `implementations/ruby/browsers-and-transactions` ▶︎ contains several TODO's Note: No active pages link here
- `implementations/ruby/console-colours` ▶︎ TODO: Review. Note: No active pages link here- 
- ~~`implementations/perl` ▶︎ TODO: Review~~ (Merged/deleted) 

## Tasks
- [x] `implementations/ruby/custom-formatters` ▶︎ TODO: fix link ▶︎ Does not contain any broken links, removed the 'TODO'
- [x] `cucumber/step-organization`▶︎  TODO: integrate with step definitions and/or anti-patterns => Suggestion: merge & rewrite to make `Good practices`? ▶︎ DONE (PR #77) 
- [x] `cucumber/running features` ▶︎ TODO: Generalize ▶︎ DONE (PR #75) 
- [x] `cucumber/mocking and stubbing` ▶︎ TODO: Generalize and update ▶︎ DONE (PR #71)
- [x] `cucumber/checking assertions` ▶︎ TODO: generalize (atm it has Ruby only) ▶︎ In progress, see PR #69 (Could maybe use more info on Javascript)
- [x] `cucumber/tags` ▶︎ TODO: Gherkin and Cucumber. This is mostly Cucumber ▶︎ DONE (PR #63)
- [x] `gherkin/feature-introduction` ▶︎ TODO: Gherkin reference ▶︎ DONE (PR #59) 
- [x] `about/get in touch` ▶︎ Suggestion: Replace with info from current 'Support'-page (https://cucumber.io/support) and move info about issues to contributing? ▶︎ DONE (PR #58) 
- [x] `cucumber/hooks` ▶︎ TODO: Important. Generalize. ▶︎ DONE (PR #56)
- [x] `gherkin/background` ▶︎ TODO: Review. Add to gherkin reference ▶︎ DONE (PR #56) 
- [x] `about/related tools` - TODO: Clean and delete. Move to json? ▶︎ DONE (PR #45)
- [x] `cucumber/browser automation/#Watir` ▶︎ DONE (PR #39)
- [x]  `cucumber/feature coupled step definition (antipattern)` ▶︎ TODO: Generalize. Move to Step Definitions (atm ruby only, adding java) ▶︎ DONE (PR #39)
- [x] `cucumber/step-definitions` ▶︎ Some Ruby specific content ("_Where_ are Step Definitions?") ▶︎ DONE (PR #50)
- [x] `implementations/ruby/calling-steps-from-stepdefinitions` ▶︎ DONE (PR #50)
- [x] Suggestion: merge step-definitions-old.md and step-definitions.md ▶︎ DONE (PR #50)

----
**Edit by Zearin** : Formatting to help read the long list :)

**Comment by Zearin** [comment]
A large number of those TODOs mention “generalize”.  

What exactly are they referring to?  I mean, generalize _what_?

**Comment by mlvandijk** [comment]
@Zearin, most likely it means making sure the text is valid for all languages/implementations, so not specific to only one language.

**Comment by Zearin** [comment]
@mlvandijk Thanks.  That resolves a lot of confusion on my end. :)

**Comment by mlvandijk** [comment]
@Zearin Yw. Maybe you could help to generalize the Ruby specific texts? Most of my review comments on your PR#31 are actually related to this (and not the capitalization).

**Comment by olleolleolle** [comment]
@mlvandijk This huge undertaking is going well!

(I edited the _Description_ of this PR to render checkboxes. Visualizing progress!)

**Comment by mlvandijk** [comment]
Thanks @olleolleolle !

**Comment by mlvandijk** [comment]
Closed, moved to #130
