### ISSUE TITLE
Add missing docs in new menu structure

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#80]
A list of missing (or incomplete) pages in the new menu structure:
- [ ] "Documentation" ▶︎ *Write a brief intro?*
- [ ] Guides/10 minute tutorial (JavaScript) ▶︎ **Write new content** ▶︎ see #103
- [ ] Guides/10 minute tutorial (Ruby) ▶︎ **Write new content** ▶︎ see #104

## Tasks
- [x] Guides/BDD tutorial (Java) ▶︎ DONE (PR #93)
- [x] Guides/Testable Architecture "How to have fast and reliable tests" ▶︎ DONE (PR #86) 
- [x] Guides/Browser Automation (NB. Marked "Old") ▶︎ DONE  (PR #83 )
- [x] Documentation/Configuration ▶︎ TODO: Move content from other places ▶︎ DONE  (PR #85)
- [x] Documentation/Overview - "a gentle introduction to Cucumber" ▶︎ DONE (PR #81) 
- [x] BDD/Who does what ▶︎ DONE (PR #81) 
- [x] BDD/Example Mapping ▶︎ TODO: Short version of Matt’s Example Mapping article, link to blog: https://cucumber.io/blog/2015/12/08/example-mapping-introduction  ▶︎ DONE (PR #81)

**Comment by mlvandijk** [comment]
Closing this issue as docs have either been written or (part of) other issue
